export interface AtendimentoDTO {
  id_atend_proc: number,
  id_profissional: number,
  id_procedimento: number,
  id_atendimento: number,
  id_paciente: number,
  valor_total_procedimento: number,
  valor_total_comissao: number,
  data: Date,
  valor_procedimento: number,
  valor_comissao: number,
  procedimento_realizado: boolean,
  nome_paciente: string,
  email_paciente: string,
  telefone_paciente: string,
  nome_procedimento: string,
  percentual_comissao: number,
  nome_profissional: string,
  email_profissional: string,
  telefone_profissional: string,
}
